### ISSUE TITLE
Implement a synchronization script to add authors of existing proposals to peerdoc

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#1001]
For all existing proposals, write a script that will post creators as admins  and other authors as editors of the peerdoc associated to the proposal

**Comment by mitar** [comment]
Didn't we decide that everyone should be added as admins for now to PeerDoc?

**Comment by cdparra** [comment]
Yes, but the issue was created before that. @yolile  implemented the right version though

**Comment by mitar** [comment]
Also, just to make sure, besides syncing permissions, also visibility should be synced. To my understanding no existing proposal should be public, but if it is, then this has to be synced to PeerDoc.

**Comment by mitar** [comment]
I am also seeing many such errors in the log on PeerDoc:

```
Error handling /document/share API request. Error: Document cannot be found. [not-found]
```

Are you sure requests went through? Or that you were making correct URIs? But maybe AppCivist has more documents than they are in PeerDoc for some reason.

**Comment by cdparra** [comment]
In the testing database we still have everything that was created before the reset of the PeerDoc database. Surely, some of these errors corresponds to those contributions.
