### ISSUE TITLE
Contributions update issues 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#159]
In a nutshell, every update triggers deletes on users and resource spaces or prompts the creation of related entities in the resource space that already exists. 

Possible solutions: 
- [ ] Have multiple endpoints and make PUT /contribution to only edit first level attributes
- [ ] Modify the contribution model to give the resourceSpace a setter.

**Comment by javierpf** [comment]
Updated business logic in the backend. Only first level attributes are being updated in this endpoint. Associations remain untouched.
Separate endpoints made for associations updates are already available. See #315
