### ISSUE TITLE
Update the voting-api (in rails) to make sure the ballot creation includes the list of proposal UUIDs as candidates

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#279]
This issue is related to this repository socialappslab/appcivist-voting-api

When creating a new ballot, the API should also accept the following: 
1. Type of candidates (contributions, assemblies, campaigns, users, working groups)
2. A list of UUIDs that represent candidates in the main database

Notes: check what else is needed in the candidates model

**Comment by cdparra** [comment]
@javierpf some of these have defaults in the database (can't remember which),but just incase, should be like this 
removed = false
removed_at timestamp without time zone = null
require_registration boolean = false
user_uuid_as_signature boolean = true
decision_type character varying(40),
component = null (it might go beyond one campaign component, so better we don't use this, check if it is required and eliminate that requirement) 
status integer = ACTIVE (is an enum, let's try to make it a STRING in the database rather than an integer)

**Comment by javierpf** [comment]
@cdparra Have not found this defaults in database. Should I create them?

**Comment by cdparra** [comment]
Yes, let's create these defaults and make sure they are applied on the appcivist models too
