### ISSUE TITLE
QA Testing and Review of Notifications

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#287]
- [x] Install, configure and run the [binding components of the socialbus](https://github.com/socialappslab/socialbus-bc), check what's missing in the documentation to make this work. These binding components serve as a interface to rabbitmq to push messages through multiple channels (smpt, social networks, etc.). We used them to send notification messages via email (and will use them in the future as the main communication backbone for appcivist) 
- [x] Install and run the [notifications server](https://github.com/socialappslab/appcivist-notification-service), which receives requests from the core-backend of appcivist and resends them to the proper socialbus binding component, depending on the channel choses for the notificaiton (e.g., email) 
- [x] Prepare a testing unit to check the following
       1. When we subscribe to a resource space, all the proper events and subscriptions are created in the notification service
       2. When an event occurs (e.g., a contribution is created in a working group, or a comment in a proposal, or a comment in the campaign, or a new assembly, campaign, working group, etc.), the signal is sent to the notification service
       3. the notification service sends the message to the proper binding component
       4. the email is received with the notification

**Comment by javierpf** [comment]
Could you elaborate this description a little more?

**Comment by cdparra** [comment]
@javierpf just added the details now

**Comment by cdparra** [comment]
@javierpf is there a Pull Request with the testing unit?
