### ISSUE TITLE
Debug creation of assemblies, working groups and campaigns

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#335]
Let's review the forms and make sure the work properly. 

Here is a list of things ToDo: 

**Campaign Creation**
- [ ] Remove the following
![image](https://cloud.githubusercontent.com/assets/630150/23368931/4fceb3b4-fcee-11e6-87e4-0eb8a4783f2b.png)

-  [ ] Replace the "Stage and timelines with the following" (notice we are reusing the timeline from the campaign dashboard): 
[Campaign Configuration Timeline Configuration.pdf](https://drive.google.com/open?id=0B7ShzcEnCJFNU09ZakZaT0I5ZGM)

**Assembly Creation**
This one seems to work well, except for:  
UI Issues
- [ ] Put phrases that appears in between $$$ in the translation files
- [X] Shortname must be unique
- [ ] Add preview of icon uploaded
- [ ] Add option to upload a cover picture (by default, use URL used for the landing page background)
- [ ] Instead of "assembly themes" let's use the word "assembly categories"
- [ ] Let's use tinbymce editor for the invitation email 
- [ ] Add back the checkboxes for the invitations to select if the user is coordinator or not
- [ ] Create New Assembly should set principalassembly to TRUE
- [ ] Add "(coming soon)" to the following configurations
Enable Forum (coming soon)
Enable moderator role
Has registration form
Membership invitation by members
Etherpad api key
Etherpad base url
Enable messaging
Face to face scheduling
- [ ] Comment-out the following (we don't need them right now) 
Has registration form ID
Has registration form URL
Api key
Assembly network
Assembly network campaign limit
Assembly network limit
Assembly network group limit
Domain
Theme
- [ ] When moving to a new assembly space (/#/assembly/:aid or :uuid) remove all the content of the other assembly 
- [ ] When signing in from /#/[assembly-short-name]/login load only the campaigns and working groups of that assembly (not of the principal assembly)
- [ ] When signing out, redirect to the sign in page of the current assembly
- [ ] add preview of picture uploaded for the assembly icon

Backend issues: 
- [ ] Make sure the icon defaults are updated to the right domain: replace appcivist.littlemacondo.com to platform.appcivist.org
- [ ] Disable email invitations until we hava a new version of the invitation accepting page

**Comment by cdparra** [comment]
[New version of the default timeline example for the campaign (will be served by the backend):](http://www.jsoneditoronline.org/?id=66671ca8aca18932d50d33962a3bfa2f)

Some notes: 
1. For each component (i.e., Phase), what's important is the `title` and the `description`
2. For each milestone what's important is the `title`, the `description` and the `date`. The first milestone is always of type START, the last always of type END, the middle ones always of type REMINDER
3. For each config, what's important is `key` and `value`. To describe the config, see the `configDefinition` property. Next comment is an explanation about how to use the fields of the config definition.

**Comment by cdparra** [comment]
Also important for each component is the `type`. The user can select the type of component he wants to add or edit the one currently selected. 

component types = `IDEAS, PROPOSALS, DELIBERATION, VOTING, IMPLEMENTATION`

**Comment by cdparra** [comment]
Other issues found while debugging that we need to clear out when we deal with the ticket about finishing creation patterns: 
- [ ] "My Working Groups" In the UI should list only the working groups of the currentCampaign (there should be an endpoint for this)
- [ ] Working Group in the new proposal form should include only working groups of current campaign
- [ ] In the UI, emphasize which one is the current campaign in the list of the menu
- [ ] There should be an option to decide whether we want emails sent massively when we create an assembly and working group

**Comment by jorgeramirez** [comment]
@cdparra work in progress at https://github.com/socialappslab/appcivist-pb-client/tree/feature%23335

**Comment by cdparra** [comment]
Follow up on #443
