### ISSUE TITLE
Add "isTopic" support in Working Groups

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#339]
- [ ] Add isTopic as boolean in WG model
- [ ] Add isTopic control in membership dynamics (if TRUE, treat WG as OPEN) 
- [ ] If isTopic translate always to Topic instead than Working Group

**Comment by MarceMMAD** [comment]
@cdparra una consulta, lo de "If isTopic translate always to Topic instead than Working Group" es del lado del front end no?
