### ISSUE TITLE
Implement reading and updating configurations in a resource space

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#341]
- [ ]  GET /space/:id/config should return a hashmap of configs in tha space with the format
```json 
{
  "key1" : "value1", 
  "key2" : "value2"
... 
}
```

- [ ]  PUT /space/:id/config should update the values in the body
- [ ] POST /space/:id/config should add a new config

**Comment by javierpf** [comment]
@cdparra and what about authorization? Will we only ask for logged user?

**Comment by javierpf** [comment]
@cdparra For example, a resource space has 2 configs. For get endopint correct if it's not the expected result
GET /space/:id/config
{
  "assembly.face-to-face.scheduling": "true",
  "assembly.enable.messaging": "true"
}

**Comment by javierpf** [comment]
@cdparra For the POST and PUT endpoints do i have to receive a JSON of multiples configs? And for each config object do i have to expect a complete JSON with all his attributes or a hashmap only with key:value?

**Comment by cdparra** [comment]
@javierpf 
**About authorization:** good question. We need to make configurations available for public/anonymous sites to work, so let's start without requesting anything, making configs effectively public. This is, however, a problem, since configuration have a political dimension. I will think about the authorization question and open another ticket later one when we have a better answer. 

**For the GET:** I think that if we can return a key:value version, that would be the most optimal for the UI. We need to make this available with the space id, but also with the space UUID (for public sites). 

**For POST/PUT:** if it is not difficult to make an operation that takes a group of configs in <key,value> format, then let's go for this version that is easier for UIs to manage.
