### ISSUE TITLE
Implement Organization model

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#365]
Organization must have: 
- [ ] title
- [ ] description
- [ ] logo => Resource with URL

- [ ] Assemblies must have a ManyToMany association with Organizations. To allow future associations with other entities, let's add the association to the resource space.  

- [ ] Make sure the create assembly functionality creates the records for the Organizations, or re-uses existing ones if they are indicated.

**Comment by javierpf** [comment]
@cdparra Does it requires any additional endpoints?

**Comment by cdparra** [comment]
@javierpf For the creation, I would say no: let's allow the user create organizations as part of the process of creating an assembly

To edit the assembly, we will need extra endpoints to add/delete organizations from the assembly resource space. In fact, I think that we need GET/PUT/DELETE endpoints for all the entities we generally associate to resource spaces, to read, add and delete entities from those ResourceSpaces. I would make sure we have at least GET/PUT/DELETE for the following:

* Assemblies
* Ballots
* Campaigns
* Campaigns Components
* Campaign Milestones
* Configs
* Contributions
* Themes
* Resource
* Working Groups

The tricky part is to create the "access controls for all of these. 

Let's do the GET/PUT/DELETE of Organizations from the resource space as part of this ticket and we will do the others in upcoming sprints.
