### ISSUE TITLE
Check the Assembly homepage design and comment what endpoints are needed for each piece of information

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#367]
The homepage design is in [appcivist-pb-client#416](https://github.com/socialappslab/appcivist-pb-client/issues/416)

**Comment by javierpf** [comment]
GET       /api/assembly/:uuid/campaign
This endpoint has the filter option with "ongoing" and "all" options already implemented to return campaigns
GET      /api/space/:sid/organization
This endpoint returns all the organizations of a resource space, in this case of the assembly resource space
GET       /api/assembly/:aid/campaign/:cid/resources
This endpoint returns all the resources of the campaign
refs socialappslab/appcivist-pb-client/issues/417

**Comment by cdparra** [comment]
@jorgeramirez for your reference, take a look to this ☝️ 
@javierpf don't we have a `[GET|POST] /api/space/:sid/resources`? If not, we need to create it now so that we can use that one to get the list of resources of the Assembly (that's what we need in this homepage)

**Comment by javierpf** [comment]
@cdparra we don't. Will you add a separate ticket for this?
