### ISSUE TITLE
GET/PUT/DELETE endpoints for all the entities that can be associated to resource spaces

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#369]
GET/PUT/DELETE endpoints for all the entities we generally associate to resource spaces, to read, add and delete entities from those ResourceSpaces. I would make sure we have at least GET/PUT/DELETE for the following:

- [x] Assemblies
- [x] Ballots
- [x] Campaigns
- [x] Campaigns Components
- [x] Campaign Milestones
- [x] Configs
- [x] Contributions
- [x] Themes
- [x] Resource
- [x] Working Groups

In the first version, we will implement a simple access control using the following rules: 
1. In all cases, there should be a public version that uses the space uuid and returns the objects with their public view attributes
1. GET endpoints are available to all members, unless there is an specific anonymous enpdoint that uses the space UUID, in which case is public
2. Except for contributions, PUT/DELETE operations are allowed only to  **Assembly Coordinators** if the resource space is of type ASSEMBLY, and to **Working Group Coordinators** if the resource space is of type WORKING_GROUP: 
3. Contributions of all types (except DISCUSSION and COMMENT) can be PUT/DELETE to all members of the assembly if the resource space is of type ASSEMBLY, and to all members of the WG if the resource space is of type WORKING_GROUP
4. Contributions of type DISCUSSION and COMMENT are allowed to all members of the assembly and to anyone if the endpoint is by UUID
5. If the resource space is of type CONTRIBUTION, authors can do what coordinators do in assemblies, campaigns and working groups.

**Comment by cdparra** [comment]
Some of these are done, the idea is to complete and unify them in the same controller

**Comment by javierpf** [comment]
@cdparra PUT/DELETE endpoints are only for add and delete entities from ResourceSpaces? Or it also updates their attributes?

**Comment by javierpf** [comment]
@cdparra GET endpoints lists all the entities of a resource space? 
GET /space/id/entity
or return a single entity by ID?
GET /space/id/entity/eid

**Comment by cdparra** [comment]
@javierpf: 
1. Let's have also UPDATE endpoints
2. We need both: 
     * GET /space/:sid/entity => List (perhaps with a query param search=? that performs a search in the title and description of the entity) 
     * GET /space/:sid/entity/:eid => the single entity
