### ISSUE TITLE
Add support for entity custom fields

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#382]
- [ ] Add model `CustomFieldDefinition` with the attribures: 
     * `Long id` unique identifier 
     * `String name` of the custom field
     * `String description` of the custom field
     * `String entityType` that represents what the fields extends. can be Assembly, Campaign, Working Group, Component, Milestone, Contribution, ContributionFeedback
    * ` String entitySubType` used when there is an additional qualifier for the main type, for example, with contributions we have IDEA, PROPOSAL, COMMENT, DISCUSSION
    * `Integer position` that determines the ordering of the extended fields
    * `String limit` to indicate the limit for the value of the custom field
    * `String limitType` (WORDS, CHARS (default), FILE_SIZE) to describe what type of limit should the field have

- [ ] Add relationship of customfielddefinition with resource spaces
- [ ] Add model for `CustomFieldValue` with the following fields: 
       * `String entityTargetType`: ASSEMBLY, CAMPAIGN, WORKING_GROUP, COMPONENT, MILESTONE, CONTRIBUTION, CONTRIBUTION_FEEDBACK
      *  `String entityTargetUUID`: UUID of the actual instance of the entityTargetType that this custom field value is extending
      * `String value`: string that contains the actual value defined by the user
 
- [ ] Add `[GET|POST|PUT|DELETE] /space/:sid/field` endpoints to implement CRUD operations of custom field definitions in various resource spaces

**Comment by javierpf** [comment]
@cdparra Can we elaborate here the complete list of available options for each enum (entityType, entitySubType, limitType and entityTargetType) described here?

**Comment by cdparra** [comment]
@javierpf @jruax56 

See below the specs: 
* First, let's make sure the list remains open in the database (we can use an enum in the code but the DB can remain as a TEXT field) as we will add other values in the future. The ones below is the default list of values
* `entityType`: this will indicate what entity (i.e., AppCivist Model) will be extended with this custom field => `[ASSEMBLY, CAMPAIGN, WORKING_GROUP, COMPONENT, MILESTONE, CONTRIBUTION, CONTRIBUTION_FEEDBACK, BALLOT]`
* Instead than `entitySubType` let's use `entityFilter` and `entityFilterAttributeName`: this will be used to only apply the custom field to entities of `entityType` that correspond to the filter. Both are text fields. 
* `entityFilterAttributeName` stores the name of the field in `entityType` that we use to filter (e.g., `type` for `CONTRIBUTION`, `template.nameKey` in `CAMPAIGN`, `profile.managementType` in `WORKING_GROUP`). 
* `entityFilter` would be the value used to filter `entityType` by its `entityTypeAttributeName` (e.g., CONTRIBUTION of type `PROPOSAL`, WORKING_GROUP that are `OPEN`, CAMPAIGNS of template `PARTICIPATORY_BUDGETING`)

**Comment by cdparra** [comment]
For `limitType`, the need is the following: custom fields might have limits. An exemplary use case is: "I want proposals to have a poster. The poster should have no more than **2 pictures**, each no greater than **10Mb**. It should also have a title of **50 chars** and an abstract of **100 words**". The `limit` field would contain the value (e.g.,  `10`, `50`, etc.). The `limitType` would indicate the type of limit (`chars`, `words`, `file size`). Let's start with these three.

**Comment by cdparra** [comment]
In the `CustomFieldValue`, we need to identify to what entity (i.e., table) the `entityTargetUUID` refers to. So the values are the same as those for `entityType` in the custom field definition. In this implementation, `CustomFieldValue` and `CustomFieldDefinition` are decoupled. We can get rid of `entityTargetType` here if we have this entity associated to the definition (which I think would be fine, but even with the association I think I prefer to have this value here so that we can maybe have an index and optimize queries.
