### ISSUE TITLE
Internal changes not shown in the history

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#383]

**Comment by javierpf** [comment]
@cdparra Can you describe the issue here?

**Comment by javierpf** [comment]
![image](https://cloud.githubusercontent.com/assets/740238/24771673/6f1e25e0-1adc-11e7-9b36-3cfc64960eda.png)
@cdparra  I did a test, making internal changes in a contribution. The changes appear in the history, as shown in the image. Could you provide more information to replicate this issue?

**Comment by cdparra** [comment]
I am not being able to reproduce this, so marking it as invalid and closing.
