### ISSUE TITLE
Add template endpoints for the creation operations

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#384]
- [ ] Change the campaign template route to GET `/api/template/campaign/default`
- [ ] Implement GET `/api/template/assembly/default` using a default json that will be provided by @cdparra
- [ ] Implement GET `/api/template/group/default` using a default json that will be provided by @cdparra

JSONS will be available in `/conf/initial-data/configs/defaultXYZ` where XYZ = campaign, group or Assembly

**Comment by jruax56** [comment]
@cdparra Where can i find this jsons?

**Comment by cdparra** [comment]
@jruax56 not ready yet, so far, only the config definitions are there. I will be adding the default JSONS for Assembly and Group asap

**Comment by cdparra** [comment]
@jruax56 JSONs are ready now on the folder indicated in the description

**Comment by jruax56** [comment]
@cdparra Campaign it's already implemented in GET /api/template/campaign/default. I use the file located in initial-data/configs/defaultCampaignTimeline.json with the milestones modified dates as requested in other issue, but there are 2 more jsons in the same folder:
initial-data/configs/campaignConfigDefinitions.json
initial-data/configs/campaignComponentConfigDefinitions.json
Do i have to use those? New endpoint for campaignComponent? Update campaign existing endpoint , create a new endpoint o just ignore this files?

**Comment by cdparra** [comment]
@jruax56 yes, campaign is done, we just want to change the route for that one. And no, you don't have to use the config definitions yet because they are already integrated int the default campaign timeline. We will use those others field in a second iteration of these endpoints, when we will generate the default timeline from these other jsons. So, for the moment, just ignore those files.
