### ISSUE TITLE
Endpoints to add/delete authors and themes

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#386]

**Comment by jruax56** [comment]
@cdparra Are this endpoints listed below what your asking for?
POST      /api/contribution/:uuid/themes                                  
POST      /api/contribution/:uuid/authors                                 
DELETE    /api/contribution/:uuid/themes/:tid                             
DELETE    /api/contribution/:uuid/authors/:auuid

**Comment by cdparra** [comment]
@jruax56 you are right, these are already implemented. Let's then use this ticket and the time devoted to it to create a unit test of these operations (this unit test will then become a template for progressively adding testing to the whole platform) 

[Here is how to do unit testing of controllers according to play documentation](https://www.playframework.com/documentation/2.5.x/JavaTest#Unit-testing-controllers)
