### ISSUE TITLE
Refactor the data model to reflect ideas that came after meeting with PBP

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#43]

**Comment by cdparra** [comment]
[New Core Data Model][1]
[New Core Data Model with some Comments][2]

[1]: https://drive.google.com/file/d/0B7ShzcEnCJFNT19PTC1NdDBlUjA/view?usp=sharing
[2]: https://drive.google.com/file/d/0B7ShzcEnCJFNSEtlTERnajJMX3M/view?usp=sharing

**Comment by cdparra** [comment]
Data model implementation is done by commit 546b902

**Comment by animeshpathak** [comment]
Looks good; please be sure to version the ontology model, so we know if the Java code is in sync with the model or not as time progresses

**Comment by cdparra** [comment]
Will do. As of now, the model is being versioned manually (just because there were too many things going on)
