### ISSUE TITLE
Basic service endpoints for Working Groups

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#46]
Create the basic REST endpoints and controller methods for working groups

**Routes**
**[GET  | PUT | DELETE]** /group/:id
**POST** /group/

**Parameters**
* **id** (path) = Group id (for GET/PUT/DELETE)
* **SESSION_KEY** (header) = the API session key for the User that is sending the request

**Body for POST**
```json
{
"name" : "[group name]"
"text" : "[description of group]"
"expiration" : "[expiration date]";
"isPublic" : "[true (default) |false];
"acceptRequests" : "[true (default) | false]";
"membershipRole" : "[COORDINATOR | MEMBER | VOLUNTEER | FOLLOWER]";
"assemblies" : [ { "assemblyId":"[at least one assembly to which the group is affiliated]" } ];
}```

**Notes for Group creation**
* The membership role indicates which type of members can invite others

**Comment by cdparra** [comment]
CRUD endpoints have been implemented by must be reviewed and tested to adjust them for the new model

**Comment by animeshpathak** [comment]
So, testing done manually or automatically?

**Comment by cdparra** [comment]
Yes, manually, using [postman][1] and this collection of [example requests][2]

[1]: https://www.getpostman.com/
[2]: https://github.com/socialappslab/appcivist-platform/blob/master/test/postman/appcivist-core-api.json.postman_collection
