### ISSUE TITLE
Fix lang on Contribution to match author's language

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#493]
Contribution language will be improved in two steps: 
- [ ] first, a simple fix, will use the first author's language. 
In a second step, let's integrate language detection (something like https://github.com/optimaize/language-detector) to infer the language from the text. 

- [ ] implement also an update query for SQL to update existing contributions to make them use the language of the first author (this should include updating ts_vectors document)

**Comment by cdparra** [comment]
Additional notes: 
- [ ] If authors is empty, use NonMemberAuthors[0].lang
- [ ] If nonMemberAuthors is empty, use the lang of the entity to which corresponds the resource space where we are adding the contribution. e.g., if I am adding the contribution to resource space `10`, then (1) search the entity `E` (CAMPAIGN, ASSEMBLY, etc.) that corresponds to the type of the resource space, (2) use `E.lang` as the language for the contribution
- [ ] Make sure NonMemberAuthor extends AppCivistBaseModel to include `lang`

**Comment by javierpf** [comment]
@cdparra Just created a new endpoint for update existing contributions. Run the 38.sql script, then use the endpoint first to get the new languages in the contributions, and finally run script 39.sql (this updates ts_vectors document).
