### ISSUE TITLE
Import service is currently not processing uploaded file

### ISSUE THREAD

**Issue by jorgeramirez** [socialappslab/appcivist-platform#574]
## Describe the problem/story

The contribution import service `POST /assembly/{aid}/campaign/{cid}/contribution/import` returns 200 OK but no record is added to the contribution table (idea/proposal)

## Expected behavior and actual behavior.

It should return 200 OK, as it does, and in the database new records should appear.

## Steps to reproduce the problem

POST request to the given endpoint with the attached file as sample. As a side note, the service used to work.

[samples-csv.zip](https://github.com/socialappslab/appcivist-platform/files/1203527/samples-csv.zip)

**Comment by loorely** [comment]
Support new csv structure and columns:
0 Code
1 Source
2 Cycle 5 Idea	= title
3 Description	= text
4 Theme
5 Keywords
6 Date
7 location
8 group
9 Name1
10 Phone1
11 Email1
12 Name1
13 Phone1
14 Email1

Where name, phone and email are dynamically added as contribution authors

[ideas-new3.csv.zip](https://github.com/socialappslab/appcivist-platform/files/1213422/ideas-new3.csv.zip)
