### ISSUE TITLE
NotificationEventSignal Archival job

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#611]
Once a week, archive old notifications to the `NotificationEventSignalArchive`
- [ ] Archive notifications older than a month
- [ ] Create schedule Method (not persistence) to run 1 time per week and call a postgresql function to move old register from NotificationEventSignalUser to NotificationEventSignalArchive.
- [ ] Create a postgresql function move_signals(Timestamp init) receiving the range between dates to move to  NotificationEventSignalArchive. 
The function should:
1.  select all old registers from NotificationEventSignalUser older than init parameter
2. Delete all old registers from NotificationEventSignalUser older than init parameter
3. Insert all old registers to NotificationEventSignalArchive. 

CREATE OR REPLACE FUNCTION falcon.mover_auditoria_his()
  RETURNS void AS
$BODY$
                begin
 
                  WITH tmp AS (DELETE FROM falcon.auditoria RETURNING id, instancia, proceso)
                  INSERT INTO falcon.auditoria_his (id, instancia, proceso) SELECT * FROM tmp;
 
                exception
                               when others then
                                               RAISE EXCEPTION 'ERROR. %', SQLERRM
                                               USING ERRCODE = 'ER001';
                end;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

Reference: https://www.postgresql.org/docs/9.6/static/dml-returning.html
Options: 
- Use a cronjob
- Perhaps using something like [`pgAgent`](https://www.pgadmin.org/download/pgagent-source-code/) directly in the database is better

**Comment by loorely** [comment]
Added documentation to README about pgagent
