### ISSUE TITLE
Connect Subscribe/Follow Buttons: POST /api/notification/subscription | GET /api/notification/subscription/{sid} | DELETE /api/notification/subscription/{sid}

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#700]

**Comment by gvescu** [comment]
Waiting for endpoint definition. Mostly for checking if an user is subscribed to an specific resource and its standard actions (GET, DELETE)

**Comment by cdparra** [comment]
Added the corresponding issue as a dependency @gvescu and put the issue in the current sprint for @loorely to do

**Comment by cdparra** [comment]
Should be ready now

GET       /api/user/:id/notifications => returns user signals
GET       /api/user/:id/notifications/stats  => returns user signals statistics             
PUT       /api/user/:id/notifications/:nid/read => mark notification as read
PUT       /api/user/:id/notifications/read => mark all notifications as read      
POST      /api/notification/subscription => post a subscription by specifying the object subscription (preffered method, check with @loorely )
GET       /api/notification/subscription/space/:sid    => read subscriptions in a space 
POST      /api/notification/subscription/space/:sid    => adapted from old code, creates regualr subscription to resource space  
DELETE    /api/notification/subscription/space/:sid     => adapted from old code, deletes all subscriptions to a resource space
