### ISSUE TITLE
Docker architecture documentation

### ISSUE THREAD

**Issue by loorely** [socialappslab/appcivist-platform#743]
Documentation required for docker architecture: 
- Log review. 
- DataBase access
- Run docker images. 
- Control images running. 
- Basic command using Docker. 
- Docker compose summary

**Comment by cdparra** [comment]
[Documentation]( https://docs.google.com/document/d/1hO6MxfomBV1wDZWq4Vt73M4_3g865pd4HzSoUthHX8Q/edit?usp=sharing_

[Slides (in spanish)]( https://docs.google.com/presentation/d/1IZa6hQqrVbKVHzaozPk6wwN5fPH3f8GzmWX-VqhXdds/edit#slide=id.p)
