### ISSUE TITLE
Duplicated signals

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#769]
![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/9c5be016-7f2d-432a-adab-7fe6206a538a)

**Comment by cdparra** [comment]
![image.png](https://images.zenhubusercontent.com/55ca3bba4f7a08fbb7f43c8a/8afd3fdb-cb51-4dd4-8604-1446eb931287)

**Comment by yolile** [comment]
@cdparra is the front end reading the signals by user? The backend creates a rabbitmq signal for each subscribed user using the user id as queue name
