### ISSUE TITLE
Campaign proposal are not added to campaign resource space

### ISSUE THREAD

**Issue by loorely** [socialappslab/appcivist-platform#797]
## Steps to reproduce the problem
1. Go to ppi-unifesp.appcivist.org.
2. Sign in with cdparra@berkeley.edu / cdparra@vallejo 
3. Create a proposal. 
4. Go back to campaign => the proposal is not there 
5. Check the database and you will see the contribution was created but was not added to the campaign resource space

## Solution
1. Make a backup of the production database (production `149.165.156.246`) and restore it locally. 
2. Test backend.

**Comment by cdparra** [comment]
ref 87206609-dfee-4ac0-92fd-33e11d7878b3
