### ISSUE TITLE
[URGENT] PeerDoc url null pointer exception

### ISSUE THREAD

**Issue by yolile** [socialappslab/appcivist-platform#802]
[info] application - jholston@berkeley.edu
appcivist-plataform     | java.lang.NullPointerException
appcivist-plataform     | 	at utils.services.PeerDocWrapper.userToUserData(PeerDocWrapper.java:131)
appcivist-plataform     | 	at utils.services.PeerDocWrapper.encrypt(PeerDocWrapper.java:107)
appcivist-plataform     | 	at utils.services.PeerDocWrapper.getPeerDocUrl(PeerDocWrapper.java:69)
appcivist-plataform     | 	at utils.services.PeerDocWrapper.createPad(PeerDocWrapper.java:57)
appcivist-plataform     | 	at controllers.Contributions.createPad(Contributions.java:4318)
appcivist-plataform     | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$220$$anonfun$apply$252.apply(Routes.scala:7750)
appcivist-plataform     | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$220$$anonfun$apply$252.apply(Routes.scala:7750)
appcivist-plataform     | 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
appcivist-plataform     | 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
appcivist-plataform     | 	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
appcivist-plataform

**Comment by cdparra** [comment]
@yolile this we have already fixes haven't we?

**Comment by cdparra** [comment]
Just saw we have merged this already but did not close. Closing now.
