### ISSUE TITLE
Integration of publish endpoint for PeerDoc

### ISSUE THREAD

**Issue by mitar** [socialappslab/appcivist-platform#842]
I think this is already done, I just want to document it here. So when user changes in AppCivist status to "published", AppCivist should do:

* Make a POST request to `/document/publish/<documentId>?user=<base64 encrypted user payload>` with empty JSON payload `{}`.
* Response is a JSON with `{"status": "success"}` or `{"status": "error"}`.
* This is irreversible action, once it is published it is published, it becomes public and read-only for all users (they can still comment).
* After a document is published, it is also public and visibility cannot be changed anymore (#843).
* On AppCivist side I think there should be a way for users to publish a proposal, but it should also display a warning that this is final.
* We should also make sure that users know that only published proposals until some date will be considered for next steps (it is not enough to make them public).

**Comment by cdparra** [comment]
Should be done now, closing.
