### ISSUE TITLE
Integration of visibility endpoint for PeerDoc

### ISSUE THREAD

**Issue by mitar** [socialappslab/appcivist-platform#843]
Until a proposal is published (#842), user should be able to switch between "private draft" and "public draft" mode. This is done by:
* AppCivist doing a request to `/document/share/<documentId>?user=<base64 encrypted user payload>` with JSON payload `{"visibility": true}` or `{"visibility": false}`.
* Response is a JSON with `{"status": "success"}` or `{"status": "error"}`.
* This can be switched back and forth, but just if proposal is not published.

**Comment by cdparra** [comment]
Should be done now, closing
