### ISSUE TITLE
Integration of permissions endpoint for PeerDoc

### ISSUE THREAD

**Issue by mitar** [socialappslab/appcivist-platform#846]
For "public draft" to really work, PeerDoc has to know who should have access to the document. Every time user is added or removed to a list of users who can edit the proposal, AppCivist should:
* Do a request to `/document/share/<documentId>?user=<base64 encrypted user payload>` with JSON payload:

        {
          "token_users": {
            "edit": [<user>]
          }
        }

*  Where `<user>` is a document with:
   * `avatar`: URL to an avatar image.
   * `username`: Username.
   * `email`: E-mail address.
   * `id`: AppCivist internal user ID (for future needs).
* Response is a JSON with `{"status": "success"}` or `{"status": "error"}`.

**Comment by mitar** [comment]
One question. Which user is used to make this request? The user who made the change to permissions? Can any author modify the list of authors?

**Comment by cdparra** [comment]
Yes, any author can as of now. The author who makes the change is the one that sends you this information.
