### ISSUE TITLE
Describe and/or implement API to update title and last activity

### ISSUE THREAD

**Issue by mitar** [socialappslab/appcivist-platform#847]
I think we should have only one API endpoint for both, but it could also two separate endpoints. PeerDoc can call when title and/or last activity is updated on its side. Ideally I would prefer that only one request is made, with PeerDoc `documentId` as ID for the request and that AppCivist then resolves this to internal proposal ID and updates fields accordingly (last activity should be updated only when it is newer than what AppCivist has stored). If this is too complicated, then PeerDoc can also make more queries and resolves `documentId` itself, but the question is how.

If I understand correctly, PeerDoc will authenticate with server-side username and password. How is that passed in this call?

**Comment by mitar** [comment]
Last activity could be represented in ISO 8601: `YYYY-MM-DDTHH:mm:ssZ`

**Comment by cdparra** [comment]
For updating a contribution (i.e., proposal) in AppCivist, use: 
`PUT       /api/contribution/:peerdocid?title=[peerdoctitle]&lastUpdate=[lastUpdate]`
- lastUpdate => `YYYY-MM-DD HH:mm:ss` 

This endpoint is only available for ADMIN users. Use the credentials shared via Slack and obtain a session key via using: 
- `POST      /api/user/login` 
- Body in JSON: `{"email":"[email]", "password": "[pass]"}. 
- Response: a user object in JSON that contains the attribute `sessionKey`. 

Use the session key as the header` SESSION_KEY` in your updates. The session key expires in a month, so must be renewed once a month. 

The PUT contribution has three possible answers: 200, 404 and 500. 

If you get 500, look for the error in the body: `data.statusMessage` has a summarized exception message, `data.errorTrace` has a more detailed trace of the error. You can use this to send us the detail if you have errors

**Comment by cdparra** [comment]
BASE URLs: 
- Testing => `https://testplatform.appcivist.org/api`
- Production => `https://platform.appcivist.org/api`
