### ISSUE TITLE
Bug: synchronization problem 

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#857]
so I see on my side: There was an error with your request: Unparseable date: \"\"","errorTrace":"java.text.ParseException: Unparseable date: \"\"\n\tat java.text.DateFormat.parse(DateFormat.java:366)\n\tat controllers.Contributions.putContributionByPeerDocId(Contributions.java:1189)\n\tat router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$182$$anonfun$apply$214.apply(Routes.scala:7612)\n\tat router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$182$$anonfun$apply$214...

**Comment by mitar** [comment]
If you will be fixing this, could we also make it so that timestamp is in `2018-05-02T20:15:51Z` format (ISO) and that I would send the timestamp in UTC? I think our two servers are in fact in different timezones.
