### ISSUE TITLE
Search for memberships (to add authors) improvements

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-platform#875]
Summary:
- [ ] filtrar de la lista que viene de ldap, aquellos nombres que ya se registraron (i.e., emails que ya son users), y 
- [ ] Permitir que el search query sea tipo “%word1%word2%” de manera que a que si yo busco `Cristhian Parra`, igual traiga `Cristhian Daniel Parra`. Ahora mismo no trae parece.

Description provided by @jamesholston                        

```3.  Add Authors
A.  Author lists (LDAP)
 From "add author" lists of names, filter out member who are already registered from the LDAP list on right (but keep on left list)
-- Add heading to each column:  Registrado no site  /   Ainda não registrado 

Alisson has the following suggestion [to be investigated]:
Add Author search:  show all names that contain the search terms.  For example, if I search for  "Guilherme Adamo", the list should show the result "Guilherme Franca Adamo".  Currently, if I omit the middle name Franca, I get a null return.  In other words, I need to know and type in the middle name.  It would be better if I could get "Guilherme Franca Adamo" -- which is the LDAP name -- to appear as an option by typing in any of the following:  (1) first, middle, last; (2) first and middle; (3) last name only; (4) first name only.  It may be that first name only will load too many names, but I will check with Marcello tomorrow.  

B.  Info rollover
-- Add info rollover after "Add Authors"
-- "If you do not find the person you want to add on the author list, perhaps you do not have their full or correct Unifesp Intranet name.  Ask them to give it to you and then try Add Author again."
```

**Comment by jamesholston** [comment]
@yolile 
Caros, fizemos um pequeno teste, na criação de uma proposta no Appcivist. 

Ao incluir um co-autor, sao apresentadas duas listas de nomes e o autor tambem e apresentado quando seu nome e procurado.

Sugestoes:

1) Gerar lista unica com indicador visual {imagem de perfil} ao lado das pessoas ja registradas em Appcivist ou manter as duas listas filtrando apenas as pessoas que ainda nao estao cadastradas;
2) Se a pessoas ja consta como autora ou co-autora, nao apresentar o seu nome novamente na lista da direita se ja estiver cadastrado 
IMPORTANTE: ao incluir novamente o autor o sistema apresentou um a MSG Author Already in Contribuition e o autor desapareceu da linha de autores (reaparecendo apos o Reload do Navegador).
3) Tratar o campo de digitacao da pesquisa de modo a pesquisar um ou mais termos nao importanto a ordem em que aparecam no nome das pessoas na LDAP.

Exemplo: cn=*sampaio*
Exemplo AND: (&(cn=*pietro*)(cn=*marcello*))
Exemplo OR: (|(cn=*pietro*)(cn=*marcello*))

Para refinar a pesquisa.
