### ISSUE TITLE
Email notification hyperlink

### ISSUE THREAD

**Issue by jamesholston** [socialappslab/appcivist-platform#893]
-- The link is not active (blue) in various email clients:  Thunderbird, Outlook, webmail of Unifesp.
-- It is active (blue) in:  Gmail 
-- It is also active (blue) on all the cellphones we tested (e.g., iPhone and Android [I believe the cell phones use Gmail]. 
Even if inactive, the link works as intended when copied and pasted as URL.

Example from my Thunderbird email:
![screen shot 2018-05-21 at 3 02 15 pm](https://user-images.githubusercontent.com/5572598/40322962-5f4ec5c2-5d0a-11e8-9a89-7ee105b2594d.png)

Complete "View Source" in 2 screenshots of this email notification in Thunderbird:
![view source 1](https://user-images.githubusercontent.com/5572598/40322988-79e0e852-5d0a-11e8-82c4-a9bd566b23e1.png)

![view source 2](https://user-images.githubusercontent.com/5572598/40323031-9437e6ce-5d0a-11e8-885d-a70767d699a8.png)

**Comment by mitar** [comment]
Can you share an example how this link looks? Maybe a screenshot?

**Comment by cdparra** [comment]
![image](https://user-images.githubusercontent.com/630150/40270383-392ee19e-5b41-11e8-8055-f2a8c2eec4b1.png)

This is a screenshot in gmail

**Comment by mitar** [comment]
You should probably disable Sendgrid overriding e-mails to HTML (and adding tracking beacon). I think just disabling tracking beacon will probably also prevent HTML conversion.

**Comment by cdparra** [comment]
As per new screenshots posted by @jamesholston, disabling tracking didn't fix the problem
