### ISSUE TITLE
Profile first name/last name Bug

### ISSUE THREAD

**Issue by loorely** [socialappslab/appcivist-platform#907]
@loorely commented on [Wed May 23 2018](https://github.com/socialappslab/appcivist-pb-client/issues/1188)

- [ ] Debug and fix the profile update 
-- first and last name fields do not save names with spaces
-- When more than one name is added to first name, second name appears as last name
-- Change "Primeiro Nome"  =>  "Primeiro nome"

**Comment by jamesholston** [comment]
The name after a space is not saved in the text box but is saved in the nav bar as user name.  Thus, in the screenshot below, I typed Mitchell Holston in last name box.  Only Mitchell was saved in box but Mitchell Holston appeared in nav bar after first name (James).

![screen shot 2018-05-31 at 2 35 07 pm](https://user-images.githubusercontent.com/5572598/40801378-31e0aa10-64e9-11e8-9538-041c76027603.png)

**Comment by cdparra** [comment]
This is actually not a problem of the Backend, but of the frontend. 

In the profile page, two fields are displayed: 
- Name
- Lastname

And they pointo to the profile attribute of the user object: 
user.profile.name
user.profile.lastname

When the update is sent to the backend, however, everything is sent as the attribute name of the user object 
user.name

The correct way to have this would be to update our profile editing page to show
- Display name => user.name (i.e., the fullname - or nickname if user wants -  that appears in the navbar)
- Name  => user.profile.name
- Lastname => user.profile.lastname

These last two are never really shown in the UI other than in this page right now. 

And making sure that both name and lastname are included in the update object. 

Closing and opening a proper issue in FE.
