### ISSUE TITLE
New email notification template text

### ISSUE THREAD

**Issue by loorely** [socialappslab/appcivist-platform#909]
@loorely commented on [Wed May 23 2018](https://github.com/socialappslab/appcivist-pb-client/issues/1184)

- [ ] Update localization texts for authorship invitation emails as shown below (update also english and spanish version)

````
Você foi convidado a colaborar em uma proposta para o processo participativo [PPI Unifesp]. Se quiser conhecer a proposta, acesse o site do [PPI Unifesp] com o link abaixo para vê-la. Se quiser contribuir, faça o login. Depois de logado, clique em “ Compartilhadas comigo” para acessar a proposta e colaborar editando e/ou comentando. Se você não deseja colaborar, nem faça o login. É só ficar de fora e nada mais precisa fazer.
````

- [ ] Change subject of authorship email as follows 
````
Assunto: [AppCivist] Invitação para collaborar
=>
Assunto: [AppCivist] Convite para colaborar no PPI Unifesp
`````
Example: 
De: AppCivist@Socialappslab <appcivistapp@gmail.com>
Data: 16 de maio de 2018 17:49
Assunto: [AppCivist] Invitação para collaborar
Para: ctessari@gmail.com

**Comment by jamesholston** [comment]
This seems to be identical to #908.  What is missing here is the new text of the email template (TODO list item 5):

Você foi convidado a colaborar em uma proposta para o processo participativo [PPI Unifesp]. Se quiser conhecer a proposta, clique no link abaixo, faça login e comece a contribuir, editando e/ou comentando a proposta. Se você não deseja contribuir, não entre para editar. Se você não quer nem ao menos ver seu nome compartilhado na proposta, clique no link, faça login e delete seu nome.

Se você não conseguir abrir o link clicando nele, copie e cole no browser de seu computador para acessar.
